# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MasterMind.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Mastermind(object):
    def setupUi(self, Mastermind):
        Mastermind.setObjectName("Mastermind")
        Mastermind.resize(720, 950)
        self.centralwidget = QtWidgets.QWidget(Mastermind)
        self.centralwidget.setObjectName("centralwidget")
        self.frameButtons = QtWidgets.QFrame(self.centralwidget)
        self.frameButtons.setGeometry(QtCore.QRect(0, 650, 200, 250))
        self.frameButtons.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameButtons.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameButtons.setObjectName("frameButtons")
        self.Input1 = QtWidgets.QPushButton(self.frameButtons)
        self.Input1.setGeometry(QtCore.QRect(50, 50, 50, 50))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.Input1.setFont(font)
        self.Input1.setAutoFillBackground(False)
        self.Input1.setObjectName("Input1")
        self.Input4 = QtWidgets.QPushButton(self.frameButtons)
        self.Input4.setGeometry(QtCore.QRect(100, 50, 50, 50))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.Input4.setFont(font)
        self.Input4.setObjectName("Input4")
        self.Input2 = QtWidgets.QPushButton(self.frameButtons)
        self.Input2.setGeometry(QtCore.QRect(50, 100, 50, 50))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.Input2.setFont(font)
        self.Input2.setObjectName("Input2")
        self.Input3 = QtWidgets.QPushButton(self.frameButtons)
        self.Input3.setGeometry(QtCore.QRect(50, 150, 50, 50))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.Input3.setFont(font)
        self.Input3.setObjectName("Input3")
        self.Input6 = QtWidgets.QPushButton(self.frameButtons)
        self.Input6.setGeometry(QtCore.QRect(100, 150, 50, 50))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.Input6.setFont(font)
        self.Input6.setObjectName("Input6")
        self.Input5 = QtWidgets.QPushButton(self.frameButtons)
        self.Input5.setGeometry(QtCore.QRect(100, 100, 50, 50))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.Input5.setFont(font)
        self.Input5.setObjectName("Input5")
        self.label_14 = QtWidgets.QLabel(self.frameButtons)
        self.label_14.setGeometry(QtCore.QRect(0, 0, 201, 50))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setUnderline(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.NoAntialias)
        self.label_14.setFont(font)
        self.label_14.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.frameHeader = QtWidgets.QFrame(self.centralwidget)
        self.frameHeader.setGeometry(QtCore.QRect(0, 0, 200, 650))
        self.frameHeader.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameHeader.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameHeader.setObjectName("frameHeader")
        self.frameOutput = QtWidgets.QFrame(self.centralwidget)
        self.frameOutput.setGeometry(QtCore.QRect(200, 0, 300, 150))
        self.frameOutput.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameOutput.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameOutput.setObjectName("frameOutput")
        self.Try1_52 = QtWidgets.QLabel(self.frameOutput)
        self.Try1_52.setGeometry(QtCore.QRect(200, 50, 50, 50))
        self.Try1_52.setFrameShape(QtWidgets.QFrame.Box)
        self.Try1_52.setLineWidth(1)
        self.Try1_52.setMidLineWidth(0)
        self.Try1_52.setText("")
        self.Try1_52.setObjectName("Try1_52")
        self.CorrectCode2 = QtWidgets.QLabel(self.frameOutput)
        self.CorrectCode2.setGeometry(QtCore.QRect(100, 50, 50, 50))
        self.CorrectCode2.setFrameShape(QtWidgets.QFrame.Box)
        self.CorrectCode2.setLineWidth(1)
        self.CorrectCode2.setMidLineWidth(0)
        self.CorrectCode2.setText("")
        self.CorrectCode2.setObjectName("CorrectCode2")
        self.CorrectCode1 = QtWidgets.QLabel(self.frameOutput)
        self.CorrectCode1.setGeometry(QtCore.QRect(50, 50, 50, 50))
        self.CorrectCode1.setFrameShape(QtWidgets.QFrame.Box)
        self.CorrectCode1.setLineWidth(1)
        self.CorrectCode1.setMidLineWidth(0)
        self.CorrectCode1.setText("")
        self.CorrectCode1.setObjectName("CorrectCode1")
        self.CorrectCode3 = QtWidgets.QLabel(self.frameOutput)
        self.CorrectCode3.setGeometry(QtCore.QRect(150, 50, 50, 50))
        self.CorrectCode3.setFrameShape(QtWidgets.QFrame.Box)
        self.CorrectCode3.setLineWidth(1)
        self.CorrectCode3.setMidLineWidth(0)
        self.CorrectCode3.setText("")
        self.CorrectCode3.setObjectName("CorrectCode3")
        self.label_13 = QtWidgets.QLabel(self.frameOutput)
        self.label_13.setGeometry(QtCore.QRect(50, 0, 201, 50))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setUnderline(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.NoAntialias)
        self.label_13.setFont(font)
        self.label_13.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.Input = QtWidgets.QFrame(self.centralwidget)
        self.Input.setGeometry(QtCore.QRect(200, 150, 301, 751))
        self.Input.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Input.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Input.setObjectName("Input")
        self.Try1_5 = QtWidgets.QLabel(self.Input)
        self.Try1_5.setGeometry(QtCore.QRect(50, 600, 50, 50))
        self.Try1_5.setFrameShape(QtWidgets.QFrame.Box)
        self.Try1_5.setLineWidth(1)
        self.Try1_5.setMidLineWidth(0)
        self.Try1_5.setText("")
        self.Try1_5.setObjectName("Try1_5")
        self.Try1_6 = QtWidgets.QLabel(self.Input)
        self.Try1_6.setGeometry(QtCore.QRect(100, 600, 50, 50))
        self.Try1_6.setFrameShape(QtWidgets.QFrame.Box)
        self.Try1_6.setLineWidth(1)
        self.Try1_6.setMidLineWidth(0)
        self.Try1_6.setText("")
        self.Try1_6.setObjectName("Try1_6")
        self.Try1_7 = QtWidgets.QLabel(self.Input)
        self.Try1_7.setGeometry(QtCore.QRect(200, 600, 50, 50))
        self.Try1_7.setFrameShape(QtWidgets.QFrame.Box)
        self.Try1_7.setLineWidth(1)
        self.Try1_7.setMidLineWidth(0)
        self.Try1_7.setText("")
        self.Try1_7.setObjectName("Try1_7")
        self.Try1_8 = QtWidgets.QLabel(self.Input)
        self.Try1_8.setGeometry(QtCore.QRect(150, 600, 50, 50))
        self.Try1_8.setFrameShape(QtWidgets.QFrame.Box)
        self.Try1_8.setLineWidth(1)
        self.Try1_8.setMidLineWidth(0)
        self.Try1_8.setText("")
        self.Try1_8.setObjectName("Try1_8")
        self.label_15 = QtWidgets.QLabel(self.Input)
        self.label_15.setGeometry(QtCore.QRect(0, 600, 50, 50))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setUnderline(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.NoAntialias)
        self.label_15.setFont(font)
        self.label_15.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.Input)
        self.label_16.setGeometry(QtCore.QRect(0, 550, 50, 50))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setUnderline(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.NoAntialias)
        self.label_16.setFont(font)
        self.label_16.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.Try2_5 = QtWidgets.QLabel(self.Input)
        self.Try2_5.setGeometry(QtCore.QRect(200, 550, 50, 50))
        self.Try2_5.setFrameShape(QtWidgets.QFrame.Box)
        self.Try2_5.setLineWidth(1)
        self.Try2_5.setMidLineWidth(0)
        self.Try2_5.setText("")
        self.Try2_5.setObjectName("Try2_5")
        self.Try2_6 = QtWidgets.QLabel(self.Input)
        self.Try2_6.setGeometry(QtCore.QRect(150, 550, 50, 50))
        self.Try2_6.setFrameShape(QtWidgets.QFrame.Box)
        self.Try2_6.setLineWidth(1)
        self.Try2_6.setMidLineWidth(0)
        self.Try2_6.setText("")
        self.Try2_6.setObjectName("Try2_6")
        self.Try2_7 = QtWidgets.QLabel(self.Input)
        self.Try2_7.setGeometry(QtCore.QRect(100, 550, 50, 50))
        self.Try2_7.setFrameShape(QtWidgets.QFrame.Box)
        self.Try2_7.setLineWidth(1)
        self.Try2_7.setMidLineWidth(0)
        self.Try2_7.setText("")
        self.Try2_7.setObjectName("Try2_7")
        self.Try2_9 = QtWidgets.QLabel(self.Input)
        self.Try2_9.setGeometry(QtCore.QRect(50, 550, 50, 50))
        self.Try2_9.setFrameShape(QtWidgets.QFrame.Box)
        self.Try2_9.setLineWidth(1)
        self.Try2_9.setMidLineWidth(0)
        self.Try2_9.setText("")
        self.Try2_9.setObjectName("Try2_9")
        self.Try3_5 = QtWidgets.QLabel(self.Input)
        self.Try3_5.setGeometry(QtCore.QRect(150, 500, 50, 50))
        self.Try3_5.setFrameShape(QtWidgets.QFrame.Box)
        self.Try3_5.setLineWidth(1)
        self.Try3_5.setMidLineWidth(0)
        self.Try3_5.setText("")
        self.Try3_5.setObjectName("Try3_5")
        self.Try3_6 = QtWidgets.QLabel(self.Input)
        self.Try3_6.setGeometry(QtCore.QRect(200, 500, 50, 50))
        self.Try3_6.setFrameShape(QtWidgets.QFrame.Box)
        self.Try3_6.setLineWidth(1)
        self.Try3_6.setMidLineWidth(0)
        self.Try3_6.setText("")
        self.Try3_6.setObjectName("Try3_6")
        self.Try3_7 = QtWidgets.QLabel(self.Input)
        self.Try3_7.setGeometry(QtCore.QRect(100, 500, 50, 50))
        self.Try3_7.setFrameShape(QtWidgets.QFrame.Box)
        self.Try3_7.setLineWidth(1)
        self.Try3_7.setMidLineWidth(0)
        self.Try3_7.setText("")
        self.Try3_7.setObjectName("Try3_7")
        self.Try3_8 = QtWidgets.QLabel(self.Input)
        self.Try3_8.setGeometry(QtCore.QRect(50, 500, 50, 50))
        self.Try3_8.setFrameShape(QtWidgets.QFrame.Box)
        self.Try3_8.setLineWidth(1)
        self.Try3_8.setMidLineWidth(0)
        self.Try3_8.setText("")
        self.Try3_8.setObjectName("Try3_8")
        self.label_17 = QtWidgets.QLabel(self.Input)
        self.label_17.setGeometry(QtCore.QRect(0, 500, 50, 50))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setUnderline(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.NoAntialias)
        self.label_17.setFont(font)
        self.label_17.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.Try6_5 = QtWidgets.QLabel(self.Input)
        self.Try6_5.setGeometry(QtCore.QRect(50, 350, 50, 50))
        self.Try6_5.setFrameShape(QtWidgets.QFrame.Box)
        self.Try6_5.setLineWidth(1)
        self.Try6_5.setMidLineWidth(0)
        self.Try6_5.setText("")
        self.Try6_5.setObjectName("Try6_5")
        self.label_18 = QtWidgets.QLabel(self.Input)
        self.label_18.setGeometry(QtCore.QRect(0, 350, 50, 50))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setUnderline(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.NoAntialias)
        self.label_18.setFont(font)
        self.label_18.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.Try4_5 = QtWidgets.QLabel(self.Input)
        self.Try4_5.setGeometry(QtCore.QRect(150, 450, 50, 50))
        self.Try4_5.setFrameShape(QtWidgets.QFrame.Box)
        self.Try4_5.setLineWidth(1)
        self.Try4_5.setMidLineWidth(0)
        self.Try4_5.setText("")
        self.Try4_5.setObjectName("Try4_5")
        self.Try4_6 = QtWidgets.QLabel(self.Input)
        self.Try4_6.setGeometry(QtCore.QRect(200, 450, 50, 50))
        self.Try4_6.setFrameShape(QtWidgets.QFrame.Box)
        self.Try4_6.setLineWidth(1)
        self.Try4_6.setMidLineWidth(0)
        self.Try4_6.setText("")
        self.Try4_6.setObjectName("Try4_6")
        self.Try4_7 = QtWidgets.QLabel(self.Input)
        self.Try4_7.setGeometry(QtCore.QRect(100, 450, 50, 50))
        self.Try4_7.setFrameShape(QtWidgets.QFrame.Box)
        self.Try4_7.setLineWidth(1)
        self.Try4_7.setMidLineWidth(0)
        self.Try4_7.setText("")
        self.Try4_7.setObjectName("Try4_7")
        self.Try5_5 = QtWidgets.QLabel(self.Input)
        self.Try5_5.setGeometry(QtCore.QRect(200, 400, 50, 50))
        self.Try5_5.setFrameShape(QtWidgets.QFrame.Box)
        self.Try5_5.setLineWidth(1)
        self.Try5_5.setMidLineWidth(0)
        self.Try5_5.setText("")
        self.Try5_5.setObjectName("Try5_5")
        self.Try4_8 = QtWidgets.QLabel(self.Input)
        self.Try4_8.setGeometry(QtCore.QRect(50, 450, 50, 50))
        self.Try4_8.setFrameShape(QtWidgets.QFrame.Box)
        self.Try4_8.setLineWidth(1)
        self.Try4_8.setMidLineWidth(0)
        self.Try4_8.setText("")
        self.Try4_8.setObjectName("Try4_8")
        self.Try5_6 = QtWidgets.QLabel(self.Input)
        self.Try5_6.setGeometry(QtCore.QRect(150, 400, 50, 50))
        self.Try5_6.setFrameShape(QtWidgets.QFrame.Box)
        self.Try5_6.setLineWidth(1)
        self.Try5_6.setMidLineWidth(0)
        self.Try5_6.setText("")
        self.Try5_6.setObjectName("Try5_6")
        self.Try5_7 = QtWidgets.QLabel(self.Input)
        self.Try5_7.setGeometry(QtCore.QRect(100, 400, 50, 50))
        self.Try5_7.setFrameShape(QtWidgets.QFrame.Box)
        self.Try5_7.setLineWidth(1)
        self.Try5_7.setMidLineWidth(0)
        self.Try5_7.setText("")
        self.Try5_7.setObjectName("Try5_7")
        self.label_19 = QtWidgets.QLabel(self.Input)
        self.label_19.setGeometry(QtCore.QRect(0, 400, 50, 50))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setUnderline(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.NoAntialias)
        self.label_19.setFont(font)
        self.label_19.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.Try5_8 = QtWidgets.QLabel(self.Input)
        self.Try5_8.setGeometry(QtCore.QRect(50, 400, 50, 50))
        self.Try5_8.setFrameShape(QtWidgets.QFrame.Box)
        self.Try5_8.setLineWidth(1)
        self.Try5_8.setMidLineWidth(0)
        self.Try5_8.setText("")
        self.Try5_8.setObjectName("Try5_8")
        self.label_20 = QtWidgets.QLabel(self.Input)
        self.label_20.setGeometry(QtCore.QRect(0, 450, 50, 50))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setUnderline(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.NoAntialias)
        self.label_20.setFont(font)
        self.label_20.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.Try9_5 = QtWidgets.QLabel(self.Input)
        self.Try9_5.setGeometry(QtCore.QRect(50, 200, 50, 50))
        self.Try9_5.setFrameShape(QtWidgets.QFrame.Box)
        self.Try9_5.setLineWidth(1)
        self.Try9_5.setMidLineWidth(0)
        self.Try9_5.setText("")
        self.Try9_5.setObjectName("Try9_5")
        self.label_21 = QtWidgets.QLabel(self.Input)
        self.label_21.setGeometry(QtCore.QRect(0, 200, 50, 50))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setUnderline(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.NoAntialias)
        self.label_21.setFont(font)
        self.label_21.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.Try1_31 = QtWidgets.QLabel(self.Input)
        self.Try1_31.setGeometry(QtCore.QRect(50, 300, 50, 50))
        self.Try1_31.setFrameShape(QtWidgets.QFrame.Box)
        self.Try1_31.setLineWidth(1)
        self.Try1_31.setMidLineWidth(0)
        self.Try1_31.setText("")
        self.Try1_31.setObjectName("Try1_31")
        self.label_22 = QtWidgets.QLabel(self.Input)
        self.label_22.setGeometry(QtCore.QRect(0, 250, 50, 50))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setUnderline(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.NoAntialias)
        self.label_22.setFont(font)
        self.label_22.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName("label_22")
        self.Try8_5 = QtWidgets.QLabel(self.Input)
        self.Try8_5.setGeometry(QtCore.QRect(50, 250, 50, 50))
        self.Try8_5.setFrameShape(QtWidgets.QFrame.Box)
        self.Try8_5.setLineWidth(1)
        self.Try8_5.setMidLineWidth(0)
        self.Try8_5.setText("")
        self.Try8_5.setObjectName("Try8_5")
        self.label_23 = QtWidgets.QLabel(self.Input)
        self.label_23.setGeometry(QtCore.QRect(0, 300, 50, 50))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setUnderline(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.NoAntialias)
        self.label_23.setFont(font)
        self.label_23.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setObjectName("label_23")
        self.Try1_41 = QtWidgets.QLabel(self.Input)
        self.Try1_41.setGeometry(QtCore.QRect(50, 50, 50, 50))
        self.Try1_41.setFrameShape(QtWidgets.QFrame.Box)
        self.Try1_41.setLineWidth(1)
        self.Try1_41.setMidLineWidth(0)
        self.Try1_41.setText("")
        self.Try1_41.setObjectName("Try1_41")
        self.label_24 = QtWidgets.QLabel(self.Input)
        self.label_24.setGeometry(QtCore.QRect(0, 50, 50, 50))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setUnderline(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.NoAntialias)
        self.label_24.setFont(font)
        self.label_24.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_24.setObjectName("label_24")
        self.Try10_5 = QtWidgets.QLabel(self.Input)
        self.Try10_5.setGeometry(QtCore.QRect(50, 150, 50, 50))
        self.Try10_5.setFrameShape(QtWidgets.QFrame.Box)
        self.Try10_5.setLineWidth(1)
        self.Try10_5.setMidLineWidth(0)
        self.Try10_5.setText("")
        self.Try10_5.setObjectName("Try10_5")
        self.label_25 = QtWidgets.QLabel(self.Input)
        self.label_25.setGeometry(QtCore.QRect(0, 100, 50, 50))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setUnderline(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.NoAntialias)
        self.label_25.setFont(font)
        self.label_25.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_25.setAlignment(QtCore.Qt.AlignCenter)
        self.label_25.setObjectName("label_25")
        self.Try11_5 = QtWidgets.QLabel(self.Input)
        self.Try11_5.setGeometry(QtCore.QRect(50, 100, 50, 50))
        self.Try11_5.setFrameShape(QtWidgets.QFrame.Box)
        self.Try11_5.setLineWidth(1)
        self.Try11_5.setMidLineWidth(0)
        self.Try11_5.setText("")
        self.Try11_5.setObjectName("Try11_5")
        self.label_26 = QtWidgets.QLabel(self.Input)
        self.label_26.setGeometry(QtCore.QRect(0, 150, 50, 50))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setUnderline(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.NoAntialias)
        self.label_26.setFont(font)
        self.label_26.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_26.setAlignment(QtCore.Qt.AlignCenter)
        self.label_26.setObjectName("label_26")
        self.Try1_60 = QtWidgets.QLabel(self.Input)
        self.Try1_60.setGeometry(QtCore.QRect(100, 300, 50, 50))
        self.Try1_60.setFrameShape(QtWidgets.QFrame.Box)
        self.Try1_60.setLineWidth(1)
        self.Try1_60.setMidLineWidth(0)
        self.Try1_60.setText("")
        self.Try1_60.setObjectName("Try1_60")
        self.Try6_6 = QtWidgets.QLabel(self.Input)
        self.Try6_6.setGeometry(QtCore.QRect(100, 350, 50, 50))
        self.Try6_6.setFrameShape(QtWidgets.QFrame.Box)
        self.Try6_6.setLineWidth(1)
        self.Try6_6.setMidLineWidth(0)
        self.Try6_6.setText("")
        self.Try6_6.setObjectName("Try6_6")
        self.Try6_7 = QtWidgets.QLabel(self.Input)
        self.Try6_7.setGeometry(QtCore.QRect(150, 350, 50, 50))
        self.Try6_7.setFrameShape(QtWidgets.QFrame.Box)
        self.Try6_7.setLineWidth(1)
        self.Try6_7.setMidLineWidth(0)
        self.Try6_7.setText("")
        self.Try6_7.setObjectName("Try6_7")
        self.Try1_61 = QtWidgets.QLabel(self.Input)
        self.Try1_61.setGeometry(QtCore.QRect(150, 300, 50, 50))
        self.Try1_61.setFrameShape(QtWidgets.QFrame.Box)
        self.Try1_61.setLineWidth(1)
        self.Try1_61.setMidLineWidth(0)
        self.Try1_61.setText("")
        self.Try1_61.setObjectName("Try1_61")
        self.Try6_8 = QtWidgets.QLabel(self.Input)
        self.Try6_8.setGeometry(QtCore.QRect(200, 350, 50, 50))
        self.Try6_8.setFrameShape(QtWidgets.QFrame.Box)
        self.Try6_8.setLineWidth(1)
        self.Try6_8.setMidLineWidth(0)
        self.Try6_8.setText("")
        self.Try6_8.setObjectName("Try6_8")
        self.Try1_62 = QtWidgets.QLabel(self.Input)
        self.Try1_62.setGeometry(QtCore.QRect(200, 300, 50, 50))
        self.Try1_62.setFrameShape(QtWidgets.QFrame.Box)
        self.Try1_62.setLineWidth(1)
        self.Try1_62.setMidLineWidth(0)
        self.Try1_62.setText("")
        self.Try1_62.setObjectName("Try1_62")
        self.Try8_6 = QtWidgets.QLabel(self.Input)
        self.Try8_6.setGeometry(QtCore.QRect(100, 250, 50, 50))
        self.Try8_6.setFrameShape(QtWidgets.QFrame.Box)
        self.Try8_6.setLineWidth(1)
        self.Try8_6.setMidLineWidth(0)
        self.Try8_6.setText("")
        self.Try8_6.setObjectName("Try8_6")
        self.Try10_6 = QtWidgets.QLabel(self.Input)
        self.Try10_6.setGeometry(QtCore.QRect(100, 150, 50, 50))
        self.Try10_6.setFrameShape(QtWidgets.QFrame.Box)
        self.Try10_6.setLineWidth(1)
        self.Try10_6.setMidLineWidth(0)
        self.Try10_6.setText("")
        self.Try10_6.setObjectName("Try10_6")
        self.Try9_6 = QtWidgets.QLabel(self.Input)
        self.Try9_6.setGeometry(QtCore.QRect(100, 200, 50, 50))
        self.Try9_6.setFrameShape(QtWidgets.QFrame.Box)
        self.Try9_6.setLineWidth(1)
        self.Try9_6.setMidLineWidth(0)
        self.Try9_6.setText("")
        self.Try9_6.setObjectName("Try9_6")
        self.Try1_42 = QtWidgets.QLabel(self.Input)
        self.Try1_42.setGeometry(QtCore.QRect(100, 50, 50, 50))
        self.Try1_42.setFrameShape(QtWidgets.QFrame.Box)
        self.Try1_42.setLineWidth(1)
        self.Try1_42.setMidLineWidth(0)
        self.Try1_42.setText("")
        self.Try1_42.setObjectName("Try1_42")
        self.Try11_6 = QtWidgets.QLabel(self.Input)
        self.Try11_6.setGeometry(QtCore.QRect(100, 100, 50, 50))
        self.Try11_6.setFrameShape(QtWidgets.QFrame.Box)
        self.Try11_6.setLineWidth(1)
        self.Try11_6.setMidLineWidth(0)
        self.Try11_6.setText("")
        self.Try11_6.setObjectName("Try11_6")
        self.Try8_7 = QtWidgets.QLabel(self.Input)
        self.Try8_7.setGeometry(QtCore.QRect(150, 250, 50, 50))
        self.Try8_7.setFrameShape(QtWidgets.QFrame.Box)
        self.Try8_7.setLineWidth(1)
        self.Try8_7.setMidLineWidth(0)
        self.Try8_7.setText("")
        self.Try8_7.setObjectName("Try8_7")
        self.Try10_7 = QtWidgets.QLabel(self.Input)
        self.Try10_7.setGeometry(QtCore.QRect(150, 150, 50, 50))
        self.Try10_7.setFrameShape(QtWidgets.QFrame.Box)
        self.Try10_7.setLineWidth(1)
        self.Try10_7.setMidLineWidth(0)
        self.Try10_7.setText("")
        self.Try10_7.setObjectName("Try10_7")
        self.Try9_7 = QtWidgets.QLabel(self.Input)
        self.Try9_7.setGeometry(QtCore.QRect(150, 200, 50, 50))
        self.Try9_7.setFrameShape(QtWidgets.QFrame.Box)
        self.Try9_7.setLineWidth(1)
        self.Try9_7.setMidLineWidth(0)
        self.Try9_7.setText("")
        self.Try9_7.setObjectName("Try9_7")
        self.Try1_43 = QtWidgets.QLabel(self.Input)
        self.Try1_43.setGeometry(QtCore.QRect(150, 50, 50, 50))
        self.Try1_43.setFrameShape(QtWidgets.QFrame.Box)
        self.Try1_43.setLineWidth(1)
        self.Try1_43.setMidLineWidth(0)
        self.Try1_43.setText("")
        self.Try1_43.setObjectName("Try1_43")
        self.Try11_7 = QtWidgets.QLabel(self.Input)
        self.Try11_7.setGeometry(QtCore.QRect(150, 100, 50, 50))
        self.Try11_7.setFrameShape(QtWidgets.QFrame.Box)
        self.Try11_7.setLineWidth(1)
        self.Try11_7.setMidLineWidth(0)
        self.Try11_7.setText("")
        self.Try11_7.setObjectName("Try11_7")
        self.Try8_8 = QtWidgets.QLabel(self.Input)
        self.Try8_8.setGeometry(QtCore.QRect(200, 250, 50, 50))
        self.Try8_8.setFrameShape(QtWidgets.QFrame.Box)
        self.Try8_8.setLineWidth(1)
        self.Try8_8.setMidLineWidth(0)
        self.Try8_8.setText("")
        self.Try8_8.setObjectName("Try8_8")
        self.Try10_8 = QtWidgets.QLabel(self.Input)
        self.Try10_8.setGeometry(QtCore.QRect(200, 150, 50, 50))
        self.Try10_8.setFrameShape(QtWidgets.QFrame.Box)
        self.Try10_8.setLineWidth(1)
        self.Try10_8.setMidLineWidth(0)
        self.Try10_8.setText("")
        self.Try10_8.setObjectName("Try10_8")
        self.Try9_8 = QtWidgets.QLabel(self.Input)
        self.Try9_8.setGeometry(QtCore.QRect(200, 200, 50, 50))
        self.Try9_8.setFrameShape(QtWidgets.QFrame.Box)
        self.Try9_8.setLineWidth(1)
        self.Try9_8.setMidLineWidth(0)
        self.Try9_8.setText("")
        self.Try9_8.setObjectName("Try9_8")
        self.Try1_44 = QtWidgets.QLabel(self.Input)
        self.Try1_44.setGeometry(QtCore.QRect(200, 50, 50, 50))
        self.Try1_44.setFrameShape(QtWidgets.QFrame.Box)
        self.Try1_44.setLineWidth(1)
        self.Try1_44.setMidLineWidth(0)
        self.Try1_44.setText("")
        self.Try1_44.setObjectName("Try1_44")
        self.Try11_8 = QtWidgets.QLabel(self.Input)
        self.Try11_8.setGeometry(QtCore.QRect(200, 100, 50, 50))
        self.Try11_8.setFrameShape(QtWidgets.QFrame.Box)
        self.Try11_8.setLineWidth(1)
        self.Try11_8.setMidLineWidth(0)
        self.Try11_8.setText("")
        self.Try11_8.setObjectName("Try11_8")
        Mastermind.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Mastermind)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 720, 21))
        self.menubar.setObjectName("menubar")
        self.menuGame = QtWidgets.QMenu(self.menubar)
        self.menuGame.setObjectName("menuGame")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        Mastermind.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Mastermind)
        self.statusbar.setObjectName("statusbar")
        Mastermind.setStatusBar(self.statusbar)
        self.actionNew = QtWidgets.QAction(Mastermind)
        self.actionNew.setObjectName("actionNew")
        self.actionQuit = QtWidgets.QAction(Mastermind)
        self.actionQuit.setObjectName("actionQuit")
        self.actionSymbol_Amount = QtWidgets.QAction(Mastermind)
        self.actionSymbol_Amount.setObjectName("actionSymbol_Amount")
        self.actionAttempts = QtWidgets.QAction(Mastermind)
        self.actionAttempts.setObjectName("actionAttempts")
        self.menuGame.addAction(self.actionNew)
        self.menuGame.addAction(self.actionQuit)
        self.menuSettings.addAction(self.actionSymbol_Amount)
        self.menuSettings.addAction(self.actionAttempts)
        self.menubar.addAction(self.menuGame.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())

        self.retranslateUi(Mastermind)
        QtCore.QMetaObject.connectSlotsByName(Mastermind)

    def retranslateUi(self, Mastermind):
        _translate = QtCore.QCoreApplication.translate
        Mastermind.setWindowTitle(_translate("Mastermind", "MainWindow"))
        self.Input1.setText(_translate("Mastermind", "+"))
        self.Input4.setText(_translate("Mastermind", "o"))
        self.Input2.setText(_translate("Mastermind", "-"))
        self.Input3.setText(_translate("Mastermind", "x"))
        self.Input6.setText(_translate("Mastermind", "?"))
        self.Input5.setText(_translate("Mastermind", "*"))
        self.label_14.setText(_translate("Mastermind", "Symbols"))
        self.label_13.setText(_translate("Mastermind", "Answer"))
        self.label_15.setText(_translate("Mastermind", "1"))
        self.label_16.setText(_translate("Mastermind", "2"))
        self.label_17.setText(_translate("Mastermind", "3"))
        self.label_18.setText(_translate("Mastermind", "6"))
        self.label_19.setText(_translate("Mastermind", "5"))
        self.label_20.setText(_translate("Mastermind", "4"))
        self.label_21.setText(_translate("Mastermind", "9"))
        self.label_22.setText(_translate("Mastermind", "8"))
        self.label_23.setText(_translate("Mastermind", "7"))
        self.label_24.setText(_translate("Mastermind", "12"))
        self.label_25.setText(_translate("Mastermind", "11"))
        self.label_26.setText(_translate("Mastermind", "10"))
        self.menuGame.setTitle(_translate("Mastermind", "Game"))
        self.menuSettings.setTitle(_translate("Mastermind", "Settings"))
        self.actionNew.setText(_translate("Mastermind", "New"))
        self.actionQuit.setText(_translate("Mastermind", "Quit"))
        self.actionSymbol_Amount.setText(_translate("Mastermind", "Symbol Amount"))
        self.actionAttempts.setText(_translate("Mastermind", "Attempts"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Mastermind = QtWidgets.QMainWindow()
    ui = Ui_Mastermind()
    ui.setupUi(Mastermind)
    Mastermind.show()
    sys.exit(app.exec_())
