# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MasterMind.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QMainWindow
import sys



class Ui_Mastermind(object):
    def setupUi(self, Mastermind):
        Mastermind.setObjectName("Mastermind")
        Mastermind.resize(700, 950)
        self.centralwidget = QtWidgets.QWidget(Mastermind)
        self.centralwidget.setObjectName("centralwidget")
        self.frameButtons = QtWidgets.QFrame(self.centralwidget)
        self.frameButtons.setGeometry(QtCore.QRect(0, 650, 200, 250))
        self.frameButtons.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameButtons.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameButtons.setObjectName("frameButtons")
        self.Input1 = QtWidgets.QPushButton(self.frameButtons)
        self.Input1.setGeometry(QtCore.QRect(50, 50, 50, 50))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.Input1.setFont(font)
        self.Input1.setAutoFillBackground(False)
        self.Input1.setObjectName("Input1")
        self.Input4 = QtWidgets.QPushButton(self.frameButtons)
        self.Input4.setGeometry(QtCore.QRect(100, 50, 50, 50))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.Input4.setFont(font)
        self.Input4.setObjectName("Input4")
        self.Input2 = QtWidgets.QPushButton(self.frameButtons)
        self.Input2.setGeometry(QtCore.QRect(50, 100, 50, 50))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.Input2.setFont(font)
        self.Input2.setObjectName("Input2")
        self.Input3 = QtWidgets.QPushButton(self.frameButtons)
        self.Input3.setGeometry(QtCore.QRect(50, 150, 50, 50))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.Input3.setFont(font)
        self.Input3.setObjectName("Input3")
        self.Input6 = QtWidgets.QPushButton(self.frameButtons)
        self.Input6.setGeometry(QtCore.QRect(100, 150, 50, 50))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.Input6.setFont(font)
        self.Input6.setObjectName("Input6")
        self.Input5 = QtWidgets.QPushButton(self.frameButtons)
        self.Input5.setGeometry(QtCore.QRect(100, 100, 50, 50))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.Input5.setFont(font)
        self.Input5.setObjectName("Input5")
        self.LabelSymbols = QtWidgets.QLabel(self.frameButtons)
        self.LabelSymbols.setGeometry(QtCore.QRect(0, 0, 201, 50))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setUnderline(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.NoAntialias)
        self.LabelSymbols.setFont(font)
        self.LabelSymbols.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.LabelSymbols.setAlignment(QtCore.Qt.AlignCenter)
        self.LabelSymbols.setObjectName("LabelSymbols")
        self.frameHeader = QtWidgets.QFrame(self.centralwidget)
        self.frameHeader.setGeometry(QtCore.QRect(0, 0, 200, 650))
        self.frameHeader.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameHeader.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameHeader.setObjectName("frameHeader")
        self.frameOutput = QtWidgets.QFrame(self.centralwidget)
        self.frameOutput.setGeometry(QtCore.QRect(200, 0, 300, 150))
        self.frameOutput.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameOutput.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameOutput.setObjectName("frameOutput")
        self.CorrectCode4 = QtWidgets.QLabel(self.frameOutput)
        self.CorrectCode4.setGeometry(QtCore.QRect(200, 50, 50, 50))
        self.CorrectCode4.setFrameShape(QtWidgets.QFrame.Box)
        self.CorrectCode4.setLineWidth(1)
        self.CorrectCode4.setMidLineWidth(0)
        self.CorrectCode4.setText("")
        self.CorrectCode4.setObjectName("CorrectCode4")
        self.CorrectCode2 = QtWidgets.QLabel(self.frameOutput)
        self.CorrectCode2.setGeometry(QtCore.QRect(100, 50, 50, 50))
        self.CorrectCode2.setFrameShape(QtWidgets.QFrame.Box)
        self.CorrectCode2.setLineWidth(1)
        self.CorrectCode2.setMidLineWidth(0)
        self.CorrectCode2.setText("")
        self.CorrectCode2.setObjectName("CorrectCode2")
        self.CorrectCode1 = QtWidgets.QLabel(self.frameOutput)
        self.CorrectCode1.setGeometry(QtCore.QRect(50, 50, 50, 50))
        self.CorrectCode1.setFrameShape(QtWidgets.QFrame.Box)
        self.CorrectCode1.setLineWidth(1)
        self.CorrectCode1.setMidLineWidth(0)
        self.CorrectCode1.setText("")
        self.CorrectCode1.setObjectName("CorrectCode1")
        self.CorrectCode3 = QtWidgets.QLabel(self.frameOutput)
        self.CorrectCode3.setGeometry(QtCore.QRect(150, 50, 50, 50))
        self.CorrectCode3.setFrameShape(QtWidgets.QFrame.Box)
        self.CorrectCode3.setLineWidth(1)
        self.CorrectCode3.setMidLineWidth(0)
        self.CorrectCode3.setText("")
        self.CorrectCode3.setObjectName("CorrectCode3")
        self.LabeAnswer = QtWidgets.QLabel(self.frameOutput)
        self.LabeAnswer.setGeometry(QtCore.QRect(50, 0, 201, 50))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setUnderline(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.NoAntialias)
        self.LabeAnswer.setFont(font)
        self.LabeAnswer.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.LabeAnswer.setAlignment(QtCore.Qt.AlignCenter)
        self.LabeAnswer.setObjectName("LabeAnswer")
        self.Input = QtWidgets.QFrame(self.centralwidget)
        self.Input.setGeometry(QtCore.QRect(200, 150, 251, 751))
        self.Input.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Input.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Input.setObjectName("Input")
# Try 1

        self.Try1_1 = QtWidgets.QLabel(self.Input)
        self.Try1_1.setGeometry(QtCore.QRect(50, 600, 50, 50))
        self.Try1_1.setFrameShape(QtWidgets.QFrame.Box)
        self.Try1_1.setLineWidth(1)
        self.Try1_1.setMidLineWidth(0)
        self.Try1_1.setText("")
        self.Try1_1.setObjectName("Try1_1")
        self.Try1_2 = QtWidgets.QLabel(self.Input)
        self.Try1_2.setGeometry(QtCore.QRect(100, 600, 50, 50))
        self.Try1_2.setFrameShape(QtWidgets.QFrame.Box)
        self.Try1_2.setLineWidth(1)
        self.Try1_2.setMidLineWidth(0)
        self.Try1_2.setText("")
        self.Try1_2.setObjectName("Try1_2")
        self.Try1_3 = QtWidgets.QLabel(self.Input)
        self.Try1_3.setGeometry(QtCore.QRect(150, 600, 50, 50))
        self.Try1_3.setFrameShape(QtWidgets.QFrame.Box)
        self.Try1_3.setLineWidth(1)
        self.Try1_3.setMidLineWidth(0)
        self.Try1_3.setText("")
        self.Try1_3.setObjectName("Try1_3")
        self.Try1_4 = QtWidgets.QLabel(self.Input)
        self.Try1_4.setGeometry(QtCore.QRect(200, 600, 50, 50))
        self.Try1_4.setFrameShape(QtWidgets.QFrame.Box)
        self.Try1_4.setLineWidth(1)
        self.Try1_4.setMidLineWidth(0)
        self.Try1_4.setText("")
        self.Try1_4.setObjectName("Try1_4")

        self.label_151 = QtWidgets.QLabel(self.Input)
        self.label_151.setGeometry(QtCore.QRect(0, 600, 50, 50))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setUnderline(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.NoAntialias)
        self.label_151.setFont(font)
        self.label_151.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_151.setAlignment(QtCore.Qt.AlignCenter)
        self.label_151.setObjectName("label_151")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(450, 150, 51, 751))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("framePins")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(0, 600, 25, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setFrameShape(QtWidgets.QFrame.Box)
        self.label.setText("")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("pin1")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(25, 600, 25, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setFrameShape(QtWidgets.QFrame.Box)
        self.label_2.setText("")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("pin2")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(0, 625, 25, 25))
        self.label_3.setFrameShape(QtWidgets.QFrame.Box)
        self.label_3.setText("")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("pin3")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(25, 625, 25, 25))
        self.label_4.setFrameShape(QtWidgets.QFrame.Box)
        self.label_4.setText("")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("lpin")
        Mastermind.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Mastermind)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 700, 21))
        self.menubar.setObjectName("menubar")
        self.menuGame = QtWidgets.QMenu(self.menubar)
        self.menuGame.setObjectName("menuGame")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        Mastermind.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Mastermind)
        self.statusbar.setObjectName("statusbar")
        Mastermind.setStatusBar(self.statusbar)
        self.actionNew = QtWidgets.QAction(Mastermind)
        self.actionNew.setObjectName("actionNew")
        self.actionQuit = QtWidgets.QAction(Mastermind)
        self.actionQuit.setObjectName("actionQuit")
        self.actionSymbol_Amount = QtWidgets.QAction(Mastermind)
        self.actionSymbol_Amount.setObjectName("actionSymbol_Amount")
        self.actionAttempts = QtWidgets.QAction(Mastermind)
        self.actionAttempts.setObjectName("actionAttempts")
        self.menuGame.addAction(self.actionNew)
        self.menuGame.addAction(self.actionQuit)
        self.menuSettings.addAction(self.actionSymbol_Amount)
        self.menuSettings.addAction(self.actionAttempts)
        self.menubar.addAction(self.menuGame.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())

        self.retranslateUi(Mastermind)
        QtCore.QMetaObject.connectSlotsByName(Mastermind)


        self.Input1.clicked.connect(lambda: self.clicked("+"))
        self.Input2.clicked.connect(lambda: self.clicked("-"))
        self.Input3.clicked.connect(lambda: self.clicked("x"))
        self.Input4.clicked.connect(lambda: self.clicked("o"))
        self.Input5.clicked.connect(lambda: self.clicked("*"))
        self.Input6.clicked.connect(lambda: self.clicked("?"))


    def retranslateUi(self, Mastermind):
        _translate = QtCore.QCoreApplication.translate
        Mastermind.setWindowTitle(_translate("Mastermind", "MainWindow"))
        self.Input1.setText(_translate("Mastermind", "+"))
        self.Input4.setText(_translate("Mastermind", "o"))
        self.Input2.setText(_translate("Mastermind", "-"))
        self.Input3.setText(_translate("Mastermind", "x"))
        self.Input6.setText(_translate("Mastermind", "?"))
        self.Input5.setText(_translate("Mastermind", "*"))
        self.LabelSymbols.setText(_translate("Mastermind", "Symbols"))
        self.LabeAnswer.setText(_translate("Mastermind", "Answer"))
        self.label_151.setText(_translate("Mastermind", "1"))
        self.menuGame.setTitle(_translate("Mastermind", "Game"))
        self.menuSettings.setTitle(_translate("Mastermind", "Settings"))
        self.actionNew.setText(_translate("Mastermind", "New"))
        self.actionQuit.setText(_translate("Mastermind", "Quit"))
        self.actionSymbol_Amount.setText(_translate("Mastermind", "Symbol Amount"))
        self.actionAttempts.setText(_translate("Mastermind", "Attempts"))





    def clicked(self, text):
        self.Try1_1.setText(text)

        font = QtGui.QFont()
        font.setPointSize(36)
        self.Try1_1.setFont(font)
        self.Try1_1.setAutoFillBackground(False)
        self.Try1_1.setObjectName("Input1")


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Mastermind = QtWidgets.QMainWindow()
    ui = Ui_Mastermind()
    ui.setupUi(Mastermind)
    Mastermind.show()
    sys.exit(app.exec_())
